export const META_TYPE = {
  ACCOUNT_TYPE: "ACCOUNT_TYPE",
  BANK: "BANK",
  BLOOD_GROUP: "BLOOD_GROUP",
  CADRE_BATCH_NUMBER: "CADRE_BATCH_NUMBER",
  CLASS: "CLASS",
  EDUCATIONAL_RESULT: "EDUCATIONAL_RESULT",
  EDUCATIONAL_SUBJECT: "EDUCATIONAL_SUBJECT",
  EDUCATION_BOARD: "EDUCATION_BOARD",
  EDUCATIONAL_LEVEL: "EDUCATIONAL_LEVEL",
  EMS_APPLICATION: "EMS_APPLICATION",
  EXPERIENCE: "EXPERIENCE",
  GENDER: "GENDER",
  GRADE: "GRADE",
  JOINING_TYPE: "JOINING_TYPE",
  LANGUAGE: "LANGUAGE",
  LEAVE_TYPE: "LEAVE_TYPE",
  LOCATION: "LOCATION",
  LANGUAGE_ENGLISH: "LANGUAGE_ENGLISH",
  LOCATION_COUNTRY: "LOCATION_COUNTRY",
  LOCATION_DISTRICT:"LOCATION_DISTRICT",
  MARITAL_STATUS: "MARITAL_STATUS",
  MINORITIES: "MINORITIES",
  NOMINEE_TYPE: "NOMINEE_TYPE",
  NATURE_OF_DISABILITY: "NATURE_OF_DISABILITY",
  OFFICE_TYPE: "OFFICE_TYPE",
  OUTOF_CGPA: "OUTOF_CGPA",
  ORG_TYPE: "ORG_TYPE",
  POSTING_TYPE: "POSTING_TYPE",
  POSTING_INFO: "POSTING_INFO",
  PROMOTION_TYPE: "PROMOTION_TYPE",
  PUBLICATION_TYPE: "PUBLICATION_TYPE",
  PUNISHMENT_TYPE: "PUNISHMENT_TYPE",
  QUOTA: "QUOTA",
  QUOTA_DEPENDANT: "QUOTA_DEPENDANT",
  ORG_TYPE_DEPARTMENT: "ORG_TYPE_DEPARTMENT",
  ORG_TYPE_DIVISIONAL: "ORG_TYPE_DIVISIONAL",
  ORG_TYPE_DEPUTY_COMMISSIONER: "ORG_TYPE_DEPUTY_COMMISSIONER",
  RELATION: "RELATION",
  RELIGION: "RELIGION",
  SERVICE_TYPE: "SERVICE_TYPE",
  SITEMAP: "SITEMAP",
  INSTITUTION_TYPE: "INSTITUTION_TYPE",
  AWARD_TITLE: "AWARD_TITLE",
  AWARD_AREA: "AWARD_AREA",
  CADRE: "CADRE",
  TRAINING: "TRAINING",
  SOURCE_OF_FUND: "SOURCE_OF_FUND",
  FAMILY_RELATIONSHIP: "FAMILY_RELATIONSHIP",
};


export const COMMON_LABELS = {
	SL_NO: "ক্রমিক নং", // Column Header
	ACTION: "কার্যক্রম", // Column Header
	DETAILS: "বিস্তারিত", // Table Action Button
	EDIT: "সম্পাদনা", // Table Action Button
	DELETE: "মুছে ফেলুন", // Table Action Button
	SAVE: "সংরক্ষণ করুন", // Form  Button
	CANCEL: "বাতিল করুন", // Form  Button
	ACTIVE_STATUS: "প্রকৃতি",
	ACTIVE: "সক্রিয়",
	INACTIVE: "নিষ্ক্রিয়",
  NOT_ASSIGN: "তথ্য নেই",
};

export const LABELS = {
	EN:{
    MAIN_ACTIVITIES: 'Main Activities',
    EQUIPMENTS: 'Equipments', 
    ABBREVIATIONS: 'Abbreviations', 
    ATTACHED_OFFICE: 'Attached Offices', 
    SUMMARY_OF_MANPOWER: 'Summary of Manpower', 
    ALLOCATION_OF_BUSINESS: 'Allocation of Business', 
    MISCELLANEOUS: 'Miscellaneous', 
  },

  BN:{
    MAIN_ACTIVITIES: 'মূল কার্যক্রম',
    EQUIPMENTS: 'সরঞ্জামাদি', 
    ABBREVIATIONS: 'সংক্ষিপ্তরূপ সমূহ', 
    ATTACHED_OFFICE: 'সংযুক্ত অফিসসমূহ', 
    SUMMARY_OF_MANPOWER: 'জনবলের তালিকা',
    ALLOCATION_OF_BUSINESS: 'Allocation of Business',
    MISCELLANEOUS: 'বিবিধ',


  }
};