export const MENU = {
  BN: {
    TEMPLATE: "অর্গানোগ্রাম টেমপ্লেট",
    TEMPLATE_CREATE: "টেমপ্লেট তৈরি",
    EXIST_ORGANOGRAM_CREATE: "বিদ্যমান অর্গানোগ্রাম তৈরি",
    EMPLOYEE_LIST: "কর্মকর্তা/কর্মচারী",
    TEMPLATE_LIST: "টেমপ্লেট থেকে অর্গানোগ্রাম তৈরি",
    PROPOSAL_LIST: "প্রস্তাবসমূহ",
    ORGANOGRAM: "অর্গানোগ্রাম",
    APPROVED_ORGANOGRAM_LIST: "সংরক্ষিত অর্গানোগ্রামসমূহ",
    ORGANOGRAM_LIST_DRAFT: "খসড়া অর্গানোগ্রাম",
    ORGANOGRAM_LIST_INREVIEW: "পর্যালোচনাধীন অর্গানোগ্রাম",
    ORGANOGRAM_LIST_INAPPROVE: "অনুমোদনাধীন অর্গানোগ্রামসমূহ",
    POST_CONFIG: "পদবি কনফিগারেশন",
    ORANIZATION: "প্রতিষ্ঠান",
    ORANIZATION_LIST: "প্রতিষ্ঠানের তালিকা",
    ORANIZATION_TYPE: "প্রতিষ্ঠানের ধরণ",
    ORGANIZATION_GROUP: "প্রতিষ্ঠানের গ্রুপ",
    ORANIZATION_GROUP_LIST: "প্রতিষ্ঠানের গ্রুপের তালিকা",
    ORANIZATION_GROUP_TREE: "প্রতিষ্ঠানের গ্রুপের ট্রি",
    MAIN_ACTIVITY_LIST: "প্রধান কার্যাবলির তালিকা",
    ALLOCATION_OF_BUSINESS_LIST: "কর্মবন্টনের তালিকা",
    NODE_LIST: "পদবি/স্তরের তালিকা",

    ORGANOGRAM_CHANGE_TYPE: "পরিবর্তনের ধরণ",
    ORGANOGRAM_CHECKLIST: "চেকলিস্ট",
  },

  EN: {
    TEMPLATE: "Organogram Template",
    TEMPLATE_CREATE: "New Organogram Create",
    EXIST_ORGANOGRAM_CREATE: "Exist Organogram Create",
    EMPLOYEE_LIST: "Employee",
    TEMPLATE_LIST: "Organogram Create From Template",
    PROPOSAL_LIST: "Proposal List",
    ORGANOGRAM: "Organogram",
    APPROVED_ORGANOGRAM_LIST: "Approved Organograms",
    ORGANOGRAM_LIST_DRAFT: "Organogram List",
    ORGANOGRAM_LIST_INREVIEW: "Organogram List (For Review)",
    ORGANOGRAM_LIST_INAPPROVE: "Organogram List (For Approve)",
    POST_CONFIG: "Post Configuration",
    ORANIZATION: "Organization",
    ORANIZATION_LIST: "Organization List",
    ORANIZATION_TYPE: "Organization Type",
    ORGANIZATION_GROUP: "Organization Group",
    ORANIZATION_GROUP_LIST: "Organization Group List",
    ORANIZATION_GROUP_TREE: "Organization Group Tree",
    MAIN_ACTIVITY_LIST: "Main Activity List",
    ALLOCATION_OF_BUSINESS_LIST: "Business of Allocation List",
    NODE_LIST: "Node List",

    ORGANOGRAM_CHANGE_TYPE: "Change Type",
    ORGANOGRAM_CHECKLIST: "Checklist",
  },
};
