export const MENU = {
  BN: {
    TEMPLATE: "অর্গানোগ্রাম টেমপ্লেট",
    TEMPLATE_CREATE: "নতুন অর্গানোগ্রাম তৈরি",
    EMPLOYEE_LIST: "কর্মকর্তা/কর্মচারী",
    TEMPLATE_LIST: "টেমপ্লেট থেকে অর্গানোগ্রাম তৈরি",
    PROPOSAL_LIST: "প্রস্তাবসমূহ",
    ORGANOGRAM: "অর্গানোগ্রাম",
    APPROVED_ORGANOGRAM_LIST: "সংরক্ষিত অর্গানোগ্রাম সমূহ",
    ORGANOGRAM_LIST_ALL: "সকল অর্গানোগ্রাম সমূহ",
    ORGANOGRAM_LIST_INREVIEW: "পর্যালোচনাধীন অর্গানোগ্রাম সমূহ",
    ORGANOGRAM_LIST_INAPPROVE: "অনুমোদনাধীন অর্গানোগ্রাম সমূহ",
    POST_CONFIG: "পদবি কনফিগারেশন",
    ORANIZATION: "প্রতিষ্ঠান",
    ORANIZATION_LIST: "প্রতিষ্ঠানের তালিকা",
    ORANIZATION_TYPE: "প্রতিষ্ঠানের ধরণ",
  },

  EN: {
    TEMPLATE: "Organogram Template",
    TEMPLATE_CREATE: "New Organogram Create",
    EMPLOYEE_LIST: "Employee",
    TEMPLATE_LIST: "Organogram Create From Template",
    PROPOSAL_LIST: "Proposal List",
    ORGANOGRAM: "Organogram",
    APPROVED_ORGANOGRAM_LIST: "Approved Organograms",
    ORGANOGRAM_LIST_ALL: "Organogram List",
    ORGANOGRAM_LIST_INREVIEW: "Organogram List (For Review)",
    ORGANOGRAM_LIST_INAPPROVE: "Organogram List (For Approve)",
    POST_CONFIG: "Post Configuration",
    ORANIZATION: "Organization",
    ORANIZATION_LIST: "Organization List",
    ORANIZATION_TYPE: "Organization Type",
  },
};
