export const ROUTE_KEY = {
  OMS_ORG_TEMPLATE: "OMS_ORG_TEMPLATE",
  OMS_ORG_TEMPLATE_CREATE: "OMS_ORG_TEMPLATE_CREATE",
  OMS_ORG_TEMPLATE_UPDATE: "OMS_ORG_TEMPLATE_UPDATE",
  OMS_ORG_TEMPLATE_VIEW: "OMS_ORG_TEMPLATE_VIEW",
  OMS_ORG_TEMPLATE_LIST: "OMS_ORG_TEMPLATE_LIST",
  OMS_PROPOSAL_LIST: "OMS_PROPOSAL_LIST",
  OMS_ORGANOGRAM: "OMS_ORGANOGRAM",
  OMS_ORGANOGRAM_LIST: "OMS_ORGANOGRAM_LIST",
  OMS_ORGANOGRAM_VIEW: "OMS_ORGANOGRAM_VIEW",
  OMS_ORG_EMPLOYEE_LIST: "OMS_ORG_EMPLOYEE_LIST",
  OMS_POST_CONFIG: "OMS_POST_CONFIG",
};
