export const TEMPLATE_STATUS = {
  NEW: "NEW",
  IN_REVIEW: "IN_REVIEW",
  IN_APPROVE: "IN_APPROVE",
  APPROVED: "APPROVED",
};

// Auth
export const ROLES = {
  OMS_TEMPLATE_CREATE: "OMS_TEMPLATE_CREATE",
  OMS_TEMPLATE_ENTRY: "OMS_TEMPLATE_ENTRY",
  OMS_TEMPLATE_REVIEW: "OMS_TEMPLATE_REVIEW",
  OMS_TEMPLATE_APPROVE: "OMS_TEMPLATE_APPROVE",
};
